apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:

  # name: puy-ez-pong-rr0-refactor

  name: zt-1-dqn2048-v1


spec:
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  backoffLimit: 0  # 重启次数，可以为nil，表示无限重启；默认为3
  cleanPodPolicy: "Running"  # 表示job运行完成之后，如何处理worker pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作
  tasks:
  - replicas: 1
    type: none
    name: serial
    template:
      spec:
        containers:
        - name: di-container
          image: registry.sensetime.com/xlab/ding:nightly-atari  # user-defined image
          # image: registry.sensetime.com/xlab/ding:nightly-dmc2gym  # user-defined image
          imagePullPolicy: IfNotPresent
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              nvidia.com/gpu-a100: 1 # user-defined resource
              cpu: 8
              memory: "60Gi"
              # memory: "50Gi"

            limits:
              nvidia.com/gpu-a100: 1
              cpu: 8
              memory: "60Gi"
              # memory: "50Gi"

          command: ["/bin/bash", "-c",]
          args:  # user-defined execution commands
          - |
            export http_proxy=http://172.16.1.135:3128/
            export https_proxy=http://172.16.1.135:3128/
            export HTTP_PROXY=http://172.16.1.135:3128/
            export HTTPS_PROXY=http://172.16.1.135:3128/
            
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/lzero/mcts
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_az_ptree
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_mz_ctree
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_mz_ptree
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_ez_ctree
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_ez_ptree
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_sez_ctree
            #chmod -R 777 /mnt/nfs/puyuan/LightZero/data_sez_ptree
            
            cd /mnt/nfs/zhoutong/april_folder/DI-engine
            pip install -e .
            pip3 install numpy==1.22.4
            python3 -u /mnt/nfs/zhoutong/april_folder/DI-engine/dizoo/game2048/config/z1_train_2048dqn.py

            #cd /mnt/nfs/puyuan/LightZero/
            #pip install -e .
            #pip install numpy==1.22.4

            # python3 -u /mnt/nfs/puyuan/LightZero/zoo/board_games/tictactoe/config/tictactoe_alphazero_sp-mode_config.py
            # python3 -u /mnt/nfs/puyuan/LightZero/zoo/board_games/gomoku/config/gomoku_alphazero_sp-mode_config.py
            # python3 -u /mnt/nfs/puyuan/LightZero/zoo/board_games/gomoku/config/gomoku_muzero_sp-mode_config.py
            # python3 -u /mnt/nfs/puyuan/LightZero/zoo/board_games/tictactoe/config/tictactoe_muzero_sp-mode_config.py
            # python3 -u /mnt/nfs/puyuan/LightZero/zoo/atari/config/atari_efficientzero_config.py

            #python3 -u /mnt/nfs/puyuan/LightZero/zoo/classic_control/cartpole/config/cartpole_muzero_config.py
       

          volumeMounts:

          - name: cache-volume

            mountPath: /dev/shm

          - name: nfs-volume

            mountPath: /mnt/nfs/zhoutong

        volumes:

        - name: cache-volume

          emptyDir:

            medium: Memory

            sizeLimit: 128Mi

        - name: nfs-volume

          hostPath:

            path: /mnt/nfs/zhoutong
