apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: zt-2-mcts-d1
spec:
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  backoffLimit: 0  # 重启次数，可以为nil，表示无限重启；默认为3
  cleanPodPolicy: "Running"  # 表示job运行完成之后，如何处理worker pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作
  tasks:
  - replicas: 1
    type: none
    name: serial
    template:
      spec:
        containers:
        - name: di-container
          image: registry.sensetime.com/xlab/ding:nightly-atari  # user-defined image
          imagePullPolicy: IfNotPresent
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              nvidia.com/gpu-a100: 1 # user-defined resource
              cpu: 8
              memory: "50Gi"
            limits:
              nvidia.com/gpu-a100: 1
              cpu: 8
              memory: "50Gi"
          command: ["/bin/bash", "-c",]
          args: 
          - |
            export http_proxy=http://172.16.1.135:3128/
            export https_proxy=http://172.16.1.135:3128/
            export HTTP_PROXY=http://172.16.1.135:3128/
            export HTTPS_PROXY=http://172.16.1.135:3128/
            export http_proxy=http://zhoutong.p:Zt1301112.@10.1.8.50:33128/
            export https_proxy=http://zhoutong.p:Zt1301112.@10.1.8.50:33128/
            
            cd /mnt/nfs/zhoutong/april_folder/DI-engine
            pip install -e .
            pip3 install numpy==1.22.4
            cd /mnt/nfs/zhoutong/april_folder/metadrive
            pip install -e .
            cd /mnt/nfs/zhoutong/april_folder/LightZero
            pip install -e .
            python3 -u /mnt/nfs/zhoutong/april_folder/LightZero/zoo/metadrive/config/train_mcts_metadrive.py
       

          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          - name: nfs-volume
            mountPath: /mnt/nfs/zhoutong
        volumes:
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
        - name: nfs-volume
          hostPath:
            path: /mnt/nfs/zhoutong
